### ISSUE TITLE
How to migrate to use grunt-babel?

### ISSUE THREAD

**Issue by anhnt** [simonsmith/react-commonjs-example#1]
Please update this to use grunt-babel since grunt-react is deprecated now

**Comment by simonsmith** [comment]
I don't use Grunt these days. Would recommend webpack directly, or gulp.

**Comment by anhnt** [comment]
can you write an example with gulp, browserify and babel please? Sorry I'm not familiar with it

**Comment by simonsmith** [comment]
Many people have already - https://github.com/kriasoft/react-starter-kit
